# (c) Copyright 2018 by pr3d4t0r.  All rights reserved.

# vim: set fileencoding=utf-8:


version: '3'

services:
    notebook:
        container_name: 'notebook'
        environment:
            JUPYTER_LAB_ENABLE: "yes"
        image: 'jupyter/datascience-notebook'
        ports:
            - 8888:8888
        volumes:
            - './scoring:/home/jovyan/work'
            - './scoring/_jupyter:/home/jovyan/.jupyter'

